apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:p0+3B5g0mCk70urUp0CrCa8sQBBDOsAeCOkcbPSwYyDb8FxuSXph028ZZ4kqwowloI14r6FTlhVHcCSFVb7ZWNWh8bPX5oPPTaGjTtQwXyuYGdc/xlahkcdqoa5rbEGRPJTxQpVECsFPkV75okSOIQv2ncgQwQgzpTtNfYMRRNDAMZqnsFat1QeRMfZjC8yVhtmaIHD3YjjzMpLWk+B2nTZnuSxYAwxN0TA4XiGuQ1dql7rknOJX188mN/J3q0xIZ3yc/rKE66Juyv9lEogjEImMRdY47vYBrVJsJsh56A1tqEw5b+bO3EBcg23d0/ROGDNJTtTH53k=,iv:z6XJu6HIaQNon8RBDT7ABusTKTO/StU6doxBjInmrR0=,tag:RYihXSHV+BH3Hcy/Js6pgw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sop-tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12x7achf4ptnl6sxvn8r39c6puwy8423rpv8nc508gyk8xejukads3355c8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSkJrNlZwaFc3bC8rZVpW
            SUd3ek5GMU81VGJKcU9QcVF5bXhtbGx4eG5VClJmUG5iZkdvYTJneFBHUzcyR3N6
            VFUra1AybWtuRDloYjVPTnZ4eFRkbXMKLS0tIHJwZmFtSGhIVDVVWUZXM3JKemFq
            MWRzUHpIL3QyQzh1WkdEdGJlNHRRbXcKxm8O+K5Uczxpxt+053n5ks0ZQKdQTyvj
            0Jud89M33YPnmYMUxWKMHbJr46wUAAK+PvmkQuJBEl29A2e2bcUOsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-18T07:16:44Z"
    mac: ENC[AES256_GCM,data:XwbgeZlWjcpkmZkTyJl+1FMMpxTdrh0zw+jbhRUJJB3S8C+ePjbWNSybY7yA+DayCDjNTY0z6sk5bk3f38yfkGsHsu/bk1XzRNZraXnjsymr/DRtjRar6nbrb0XtFl/CEK6obQ1n5S4HFaNe5Ivc6xaJYMtqc8SRKTq9jbsXXiU=,iv:8KBCyJb1a0pFxuFW0frhbszfL63Gfrp9F2tlNltA8lU=,tag:PFfb47c8J+TLMLiWVW2K8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
