apiVersion: v1
data:
    password: ENC[AES256_GCM,data:qjrVsj4eVZ8je4zuOcKJfQ==,iv:hxaBxxgLtbhVzDcRQJAGdVvcHrFxDtKntg5aLJ5NMlE=,tag:aio3UUiuGj6IiKzhc0Ys1g==,type:str]
    user: ENC[AES256_GCM,data:fDMQkCdpzrY=,iv:eNWuY7eMah318ap+twOAjmsR83hPvXWnJ4XmLasys30=,tag:rsqKwOY8CGzo7WeAx+W/EA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12x7achf4ptnl6sxvn8r39c6puwy8423rpv8nc508gyk8xejukads3355c8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcUVUcURNRnBJamNOQ3Jx
            RElqVG1SaHZWdnNwZlVzY2thT0FtNjd1SHdvCmFsb3FhejY4RFJVVm1ka1VhbUk0
            N1ZITTg1djl1NjBpRVBjOWFUd0VYMW8KLS0tIGl0WnNQQVR1VzBGQlpldGNhSysz
            RFlnblEzTmJDZjM2cVVRRTRlNmZLWXMKI5RtKY+ycH7eWT59Ly2kTN244Lt0x58U
            IyZJu8T9w5MDC5voAZB3PvstmR9A0oPk7WC9LbPs0W+fPvuukK9u3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T21:42:58Z"
    mac: ENC[AES256_GCM,data:bqw2Uc44iBEun39gssNoN5C88yA9Ws/xzKqE07HqpkjqbRZEaoOP4CjvZw3hap9249fTKjqDf8vgvTcV0zuEIjBnH+XLvu2Sbf+sgkDoT5IkBq89v2f/sRMFODu3bEeV2wcwVxrYoLeFjhSspjAZDBgzmg5ybL42kgZj7DVex4E=,iv:1V+/B7ennX7+C/u/5n5pmHUhsLQ9zcG9bvuWO5woMUo=,tag:/X25sDw5jILDIpgu48N35Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
