apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "69.*.*"

      # version: "58.x"

      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    grafana:
      adminPassword: TempPa33
      ingress:
        enabled: true
        ingressClassName: traefik
        # annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"

        ## Labels to be added to the Ingress
        #labels: {}
        ##
        hosts:
          - grafana.philricelab.uk
        # hosts: []
        path: /
    ## TLS configuration for grafana Ingress
    ## Secret must be manually created in the namespace
        tls: []
          - secretName: grafana-tls-secret
        hosts:
          - grafana.philricelab.uk
